#
# Module manifest for module 'Format-Pester'
#
# Generated by: Erwan Quélin
#
# Generated on: 24/05/2016
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'Format-Pester.psm1'

# Version number of this module.
# If you are increasing ModuleVersion please change also the values of variable 'ScriptVersion' in the Format-Pester.ps1 file
# Verify also translations and increase the values of msg00 fields
ModuleVersion = '1.5.0'

# ID used to uniquely identify this module
GUID = 'daa609a5-1293-4f62-9467-1a120c529e87'

# Author of this module
Author = 'Erwan Quelin'

# Company or vendor of this module
#CompanyName = 'Unknown'

# Copyright statement for this module
Copyright = 'Copyright (c) 2016 Erwan Quélin and the community. All rights reserved under MIT license.'

# Description of the functionality provided by this module
Description = 'Powershell module for documenting Pester s results.'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '4.0'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @('pester','pscribo')

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
#FormatsToProcess = ''

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module
FunctionsToExport = 'Format-Pester'

# Cmdlets to export from this module
CmdletsToExport = ''

# Variables to export from this module
VariablesToExport = ''

# Aliases to export from this module
AliasesToExport = ''

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('Pester','PScribo')

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/equelin/Format-Pester/blob/master/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/equelin/Format-Pester'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = 'https://github.com/equelin/Format-Pester/blob/master/VERSIONS.md'

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}
